# Generated by Django 5.0.4 on 2026-04-16 05:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('price_volume', '裸K價量'), ('momentum', '動能/均值回歸'), ('trend', '趨勢'), ('volatility', '波動率'), ('relative', '相對強弱'), ('custom', '自定義')], max_length=32)),
                ('description', models.TextField()),
                ('params', models.JSONField(default=dict)),
                ('compute_fn', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feature_definitions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OHLCVBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ohlcv_bars',
            },
        ),
        migrations.CreateModel(
            name='StockUniverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('exchange', models.CharField(default='TWSE', max_length=16)),
                ('sector', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'stock_universe',
            },
        ),
        migrations.CreateModel(
            name='ComputedFeatureCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateField()),
                ('value', models.FloatField(null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.featuredefinition')),
            ],
            options={
                'db_table': 'computed_features',
            },
        ),
        migrations.CreateModel(
            name='FeaturePreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(related_name='presets', to='market_data.featuredefinition')),
            ],
            options={
                'db_table': 'feature_presets',
            },
        ),
    ]
