# Generated by Django 5.0.4 on 2026-04-16 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='featurepreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ohlcvbar',
            index=models.Index(fields=['ticker', '-timestamp'], name='ohlcv_bars_ticker_508854_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ohlcvbar',
            unique_together={('ticker', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='computedfeaturecache',
            index=models.Index(fields=['ticker', '-timestamp'], name='computed_fe_ticker_df4177_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='computedfeaturecache',
            unique_together={('ticker', 'feature', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='featurepreset',
            unique_together={('user', 'name')},
        ),
    ]
