# Generated by Django 5.0.4 on 2026-04-16 05:38

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_return', models.FloatField()),
                ('bh_return', models.FloatField()),
                ('annualized_ret', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
                ('calmar_ratio', models.FloatField()),
                ('max_drawdown', models.FloatField()),
                ('win_rate', models.FloatField()),
                ('turnover_rate', models.FloatField()),
                ('equity_curve', models.JSONField()),
                ('bh_curve', models.JSONField()),
                ('drawdown_curve', models.JSONField()),
                ('position_log', models.JSONField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'backtest_results',
            },
        ),
        migrations.CreateModel(
            name='LiveDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('ticker', models.CharField(max_length=20)),
                ('benchmark', models.CharField(default='0050.TW', max_length=20)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('feature_ids', models.JSONField(default=list)),
                ('hparams', models.JSONField(default=dict)),
                ('random_seed', models.IntegerField(default=42)),
                ('auto_predict_enabled', models.BooleanField(default=False)),
                ('auto_predict_time', models.TimeField(default=datetime.time(18, 10))),
                ('last_auto_predicted_for', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'live_deployments',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LivePredictionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_date', models.DateField(db_index=True)),
                ('target_date', models.DateField(db_index=True)),
                ('predicted_signal', models.CharField(max_length=8)),
                ('actual_return', models.FloatField()),
                ('predicted_return', models.FloatField(default=0.0)),
                ('realized_pnl', models.FloatField(default=0.0)),
                ('was_correct', models.BooleanField(default=False)),
                ('hit_rate', models.FloatField(default=0.0)),
                ('cumulative_pnl', models.FloatField(default=0.0)),
                ('alpha_drift', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'live_prediction_feedback',
                'ordering': ['-target_date'],
            },
        ),
        migrations.CreateModel(
            name='LiveRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('train_size', models.IntegerField(null=True)),
                ('epochs_done', models.IntegerField(default=0)),
                ('loss_history', models.JSONField(default=list)),
                ('training_window_start', models.DateField(null=True)),
                ('training_window_end', models.DateField(null=True)),
                ('artifact_path', models.CharField(blank=True, max_length=512)),
                ('prediction_date', models.DateField(db_index=True, null=True)),
                ('target_date', models.DateField(null=True)),
                ('signal', models.CharField(blank=True, choices=[('LONG', 'Long'), ('SHORT', 'Short'), ('NEUTRAL', 'Neutral')], max_length=8)),
                ('prob_long', models.FloatField(null=True)),
                ('prob_short', models.FloatField(null=True)),
                ('prob_neutral', models.FloatField(null=True)),
                ('confidence', models.FloatField(null=True)),
                ('rsi_14', models.FloatField(null=True)),
                ('vol_ann', models.FloatField(null=True)),
                ('stop_loss_pct', models.FloatField(null=True)),
                ('target_pct', models.FloatField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'live_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_path', models.CharField(max_length=512)),
                ('scaler_path', models.CharField(blank=True, max_length=512)),
                ('model_size_kb', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'model_artifacts',
            },
        ),
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arch', models.CharField(choices=[('transformer', 'Alpha Transformer'), ('lstm', 'LSTM'), ('gru', 'GRU'), ('tcn', 'Temporal Conv Net'), ('xgboost', 'XGBoost'), ('lightgbm', 'LightGBM'), ('ensemble', 'Ensemble')], max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('default_hparams', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'model_registry',
            },
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_date', models.DateField(db_index=True)),
                ('target_date', models.DateField()),
                ('signal', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short'), ('NEUTRAL', 'Neutral')], max_length=8)),
                ('prob_long', models.FloatField()),
                ('prob_short', models.FloatField()),
                ('prob_neutral', models.FloatField()),
                ('confidence', models.FloatField()),
                ('rsi_14', models.FloatField(null=True)),
                ('vol_ann', models.FloatField(null=True)),
                ('stop_loss_pct', models.FloatField(null=True)),
                ('target_pct', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prediction_records',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=8)),
                ('component', models.CharField(db_index=True, max_length=64)),
                ('message', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hparams', models.JSONField(default=dict, help_text='Hyperparameters used')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('train_size', models.IntegerField(null=True)),
                ('val_size', models.IntegerField(null=True)),
                ('test_size', models.IntegerField(null=True)),
                ('epochs_done', models.IntegerField(default=0)),
                ('loss_history', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('error_msg', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'training_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('ticker', models.CharField(max_length=20)),
                ('benchmark', models.CharField(default='0050.TW', max_length=20)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('random_seed', models.IntegerField(default=42)),
                ('split_config', models.JSONField(default=dict, help_text='{"train": 70, "val": 15, "test": 15}')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('feature_ids', models.JSONField(default=list, help_text='List of FeatureDefinition UUIDs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments', to='market_data.featurepreset')),
            ],
            options={
                'db_table': 'experiments',
                'ordering': ['-created_at'],
            },
        ),
    ]
