# Generated by Django 5.0.4 on 2026-04-16 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livedeployment',
            name='source_experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_deployments', to='ml_engine.experiment'),
        ),
        migrations.AddField(
            model_name='livedeployment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_deployments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livepredictionfeedback',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='ml_engine.livedeployment'),
        ),
        migrations.AddField(
            model_name='liverun',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ml_engine.livedeployment'),
        ),
        migrations.AddField(
            model_name='livepredictionfeedback',
            name='live_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ml_engine.liverun'),
        ),
        migrations.AddField(
            model_name='livedeployment',
            name='model_arch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ml_engine.modelregistry'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ml_engine.experiment'),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='model_arch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ml_engine.modelregistry'),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_engine.trainingrun'),
        ),
        migrations.AddField(
            model_name='modelartifact',
            name='run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='ml_engine.trainingrun'),
        ),
        migrations.AddField(
            model_name='livedeployment',
            name='source_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_deployments', to='ml_engine.trainingrun'),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backtest', to='ml_engine.trainingrun'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['component', '-created_at'], name='system_logs_compone_638ae8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='predictionrecord',
            unique_together={('run', 'prediction_date')},
        ),
    ]
